export const TAX_REFERENCE_LINKS = {
    "INCOME_TAX_RATES_BANDS": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/tax-relief-charts/index.aspx",
    "SRCOP_MARRIED_JOINT_ASSESSMENT": "https://www.revenue.ie/en/life-events-and-personal-circumstances/marital-status/marriage-and-civil-partnerships/joint-assessment.aspx",
    "MARRIED_CREDITS_AND_BANDS": "https://www.revenue.ie/en/life-events-and-personal-circumstances/marital-status/marriage-and-civil-partnerships/effect-credits-reliefs-thresholds.aspx",
    "HOW_TAX_CREDITS_WORK": "https://www.revenue.ie/en/jobs-and-pensions/calculating-your-income-tax/tax-credits.aspx",
    "USC_STANDARD_RATES_THRESHOLDS": "https://www.revenue.ie/en/jobs-and-pensions/usc/standard-rates-thresholds.aspx",
    "USC_CALCULATING": "https://www.revenue.ie/en/jobs-and-pensions/usc/calculating-usc.aspx",
    "USC_REDUCED_RATES_MEDICAL_CARD": "https://www.revenue.ie/en/jobs-and-pensions/usc/reduced-rates-of-usc.aspx",
    "USC_SELF_EMPLOYED_SURCHARGE": "https://www.revenue.ie/en/jobs-and-pensions/usc/self-employed-and-usc.aspx",
    "USC_EXEMPTION": "https://www.revenue.ie/en/jobs-and-pensions/usc/who-pays-usc.aspx",
    "PRSI_EMPLOYER": "https://www.revenue.ie/en/employing-people/paying-your-employees-tax-to-revenue/prsi.aspx",
    "PRSI_SELF_EMPLOYED": "https://www.revenue.ie/en/self-assessment-and-self-employment/guide-to-self-assessment/prsi-need-pay.aspx",
    "PRSI_RATES_DSP": "https://www.gov.ie/en/publication/6a4523-prsi-contribution-rates-for-employees/",
    "PRSI_AGE_EXEMPTION_66": "https://www.gov.ie/en/publication/6a4523-prsi-contribution-rates-for-employees/#class-j",
    "PERSONAL_CREDIT": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/marital-and-civil-status/personal-tax-credit/index.aspx",
    "EMPLOYEE_TAX_CREDIT": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/income-and-employment/employee-tax-credit/index.aspx",
    "EARNED_INCOME_CREDIT": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/income-and-employment/earned-income-credit/index.aspx",
    "AGE_TAX_CREDIT": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/health-and-age/age-credit/index.aspx",
    "BLIND_PERSONS_CREDIT": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/health-and-age/blind-persons-credit/index.aspx",
    "AGE_INCOME_EXEMPTION_65_PLUS": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/marital-and-civil-status/exemption-and-marginal-relief/index.aspx",
    "INCAPACITATED_CHILD_CREDIT": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/children/incapacitated-child-credit/index.aspx",
    "DEPENDENT_RELATIVE_CREDIT": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/health-and-age/dependent-relative/index.aspx",
    "HOME_CARER_CREDIT": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/health-and-age/home-carer/index.aspx",
    "SINGLE_PERSON_CHILD_CARER_CREDIT": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/children/single-person-child-carer/index.aspx",
    "WIDOWED_PARENT_CREDIT": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/children/widowed-parent-tax-credit/index.aspx",
    "WIDOWED_BEREAVEMENT_GUIDE": "https://www.revenue.ie/en/life-events-and-personal-circumstances/death-and-bereavement/widowed-person-or-surviving-civil-partner/index.aspx",
    "HEALTH_EXPENSES_RELIEF": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/health-and-age/health-expenses/index.aspx",
    "NURSING_HOME_FEES_RELIEF": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/health-and-age/nursing-home-and-additional-carers/index.aspx",
    "HEALTH_INSURANCE_PREMIUMS_RELIEF": "https://www.revenue.ie/en/jobs-and-pensions/taxation-of-employer-benefits/medical-insurance-premiums.aspx",
    "RENT_TAX_CREDIT": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/land-and-property/rent-credit/index.aspx",
    "RENT_TAX_CREDIT_CONDITIONS": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/land-and-property/rent-credit/qualifying-conditions.aspx",
    "RENT_A_ROOM_RELIEF": "https://www.revenue.ie/en/property/rental-income/rent-a-room-relief/index.aspx",
    "CYCLE_TO_WORK": "https://www.revenue.ie/en/jobs-and-pensions/taxation-of-employer-benefits/cycle-to-work-scheme.aspx",
    "TRAVEL_PASS_TAXSAVER": "https://www.revenue.ie/en/jobs-and-pensions/taxation-of-employer-benefits/travel-passes-bus-rail.aspx",
    "SMALL_BENEFIT_VOUCHER_EXEMPTION": "https://www.revenue.ie/en/jobs-and-pensions/taxation-of-employer-benefits/small-benefit-exemption.aspx",
    "BIK_OVERVIEW": "https://www.revenue.ie/en/jobs-and-pensions/taxation-of-employer-benefits/index.aspx",
    "FLAT_RATE_EXPENSES": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/income-and-employment/flat-rate-expenses/index.aspx",
    "PENSION_RELIEF": "https://www.revenue.ie/en/jobs-and-pensions/pension/relief/index.aspx",
    "PENSION_AGE_BASED_LIMITS": "https://www.revenue.ie/en/jobs-and-pensions/pension/relief/tax-relief-limits.aspx",
    "PENSION_AVC_PRSA": "https://www.revenue.ie/en/jobs-and-pensions/pension/relief/contributions-to-prsa-avc.aspx",
    "PENSION_RELIEF_HOW_TO_CLAIM": "https://www.revenue.ie/en/jobs-and-pensions/pension/relief/how-to-claim.aspx",
    "EIIS": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/investments-and-savings/eiis/index.aspx",
    "DEEDS_OF_COVENANT": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/donations-and-covenants/deeds-of-covenant/index.aspx",
    "DEEDS_OF_COVENANT_QUALIFYING": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/donations-and-covenants/deeds-of-covenant/covenants-that-qualify-for-relief.aspx",
    "DEEDS_OF_COVENANT_HOW_TO_CLAIM": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/donations-and-covenants/deeds-of-covenant/your-tax-responsibilities.aspx",
    "REMOTE_WORKING_RELIEF": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/income-and-employment/eworking/index.aspx",
    "TUITION_FEES_RELIEF": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/education/tuition-fees/index.aspx",
    "INCOME_PROTECTION_RELIEF": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/income-and-employment/income-continuance-plans/index.aspx",
    "CHARITABLE_DONATIONS": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/charitable-donations/index.aspx",
    "CHARITABLE_DONATIONS_HOW_TO_CLAIM": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/charitable-donations/how-to-claim.aspx",
    "MICRO_GENERATION_EXEMPTION": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/other-reliefs-and-exemptions/micro-generation.aspx",
} as const;

export type TaxLinkKey = keyof typeof TAX_REFERENCE_LINKS;

export function getTaxLink(key: TaxLinkKey | string): string | undefined {
    if (key in TAX_REFERENCE_LINKS) {
        return TAX_REFERENCE_LINKS[key as TaxLinkKey];
    }
    return undefined;
}
